spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        hbm2ddl:
          auto: update
  profiles:
    active: dev
server:
  port: 8000
myApp:
  token: 889225716:AAGEOXK3Gd2niCWbPsB71GxpbhAmrjD5jkI
